# Generated by Django 3.1.4 on 2021-01-31 14:25

from django.db import migrations, models
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('content', mdeditor.fields.MDTextField(verbose_name='本文')),
                ('snippet', models.CharField(default='', max_length=70, verbose_name='スニペット')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('release', models.BooleanField(verbose_name='公開')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name_plural': 'ブログ-コンテンツ',
            },
        ),
    ]
